name: Laravel CI

on:
  push:
    branches: [ "main" ] # Или ваша основная ветка
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name: Copy .env.example to .env
  run: php -r "file_exists('.env') || copy('.env.example', '.env');"
- name: Install Dependencies
  run: composer install --no-ansi --no-interaction --no-dev --prefer-dist
- name: Generate application key
  run: php artisan key:generate
- name: Directory Permissions
  run: chmod -R 777 storage bootstrap/cache
- name: Create Database
  run: |
    mkdir -p database
    touch database/database.sqlite
- name: Execute tests (PHPUnit) via Docker container
  run: vendor/bin/phpunit
- name: Run PHPStan
  run: vendor/bin/phpstan analyse